### ISSUE TITLE
Support ability to omit unassigned attributes

### ISSUE THREAD

**Issue by chihoyeung** [PowerDMS/Owin.Scim#9]
This is optional, but might be useful. Per schema spec:

   When a resource is expressed in
   JSON format, unassigned attributes, although they are defined in
   schema, MAY be omitted for compactness.

Not high priority, when "filter" query parameter gets implemented, the client can still choose what attributes are returned

**Comment by Cephei** [comment]
If I'm not mistaken, "filter" is used as a WHERE-type predicate.  "attributes" should be used for projection of specific members.  I've had some thoughts on how to implement this:
- ExpandoObject (dynamically populate it)
- Custom IContractResolver (http://www.newtonsoft.com/json/help/html/ContractResolver.htm)

I'm leaning towards this being a serialization-based implementation.  Instead of mapping to a dynamic dictionary I think we can easily add projection via customizing json.net.
